Document: ecomorph
Title: Debian ecomorph Manual
Author: <insert document author here>
Abstract: This manual describes what ecomorph is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ecomorph/ecomorph.sgml.gz

Format: postscript
Files: /usr/share/doc/ecomorph/ecomorph.ps.gz

Format: text
Files: /usr/share/doc/ecomorph/ecomorph.text.gz

Format: HTML
Index: /usr/share/doc/ecomorph/html/index.html
Files: /usr/share/doc/ecomorph/html/*.html
